# Generated by Django 4.2.1 on 2023-05-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(default='visitor', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_location', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='merchandise/')),
            ],
        ),
    ]
