# Generated by Django 4.2.1 on 2023-06-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(default='visitor', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_location', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='visitor', max_length=100)),
                ('contents', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('item_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.item')),
            ],
        ),
    ]
