# Generated by Django 4.2.1 on 2023-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='item',
            field=models.IntegerField(null=True),
        ),
    ]
