# Generated by Django 4.2.1 on 2023-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
