# Generated by Django 4.2.1 on 2023-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_love_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item_idx',
            field=models.IntegerField(null=True),
        ),
    ]
