# Generated by Django 4.2.1 on 2023-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_campaign_announcer_campaign_register_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('campaign', models.CharField(max_length=20)),
            ],
        ),
    ]
