# Generated by Django 4.2.1 on 2023-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='campaign',
            field=models.IntegerField(null=True),
        ),
    ]
